### ISSUE TITLE
Nested curly brackets won't get highlighted

### ISSUE THREAD

**Issue by dmstern** [rafamel/subtle-brackets#10]
In handlebars and other templating files you often have double curly brackets like

```
{{text}}
```

While there is no problem with nesting parentheses or square brackets, these double curly brackets do not get highlighted.

![Screencapture](https://media.giphy.com/media/1luxr9mEZOnXnHvmt2/giphy.gif)

**Comment by rafamel** [comment]
Hi, Daniel; thanks for taking the time to open an issue. It'll take me a little while to get on this; my time is tied up for the next week or so, but I will get to it as soon as I possibly can.

Rafa.

**Comment by rafamel** [comment]
Hi @dmstern , could you check whether this is still happening w/ the v3 release?

**Comment by rafamel** [comment]
Closing as I assume this is no longer the case.

**Comment by dmstern** [comment]
Thank you! It works! :)
