### ISSUE TITLE
Huge memory consumption, Code unstable

### ISSUE THREAD

**Issue by mosfetish** [rafamel/subtle-brackets#19]
Worked fine for a couple of months. Now huge memory leak. Disabled all extensions. Enabled only this extension. No problems. Added some extension configs to my user settings and the leak appeared. Commented out the Subtle Brackets user settings and Code is working fine again.

Win7, Code About:

Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by rafamel** [comment]
So Subtle Brackets works fine as long as there's no user setting config?

**Comment by mosfetish** [comment]
Correct.

If I have SB enabled, Code works fine. If I add a user setting, Code thrashes. If I comment out my SB user settings, Code works fine again.

**Comment by rafamel** [comment]
Just for confirmation, this happens with all other extensions disabled, and Subtle Brackets enabled, yes?

**Comment by mosfetish** [comment]
Yes. All other extensions are disabled.

SB without user settings. No Problem. 

SB with user settings. High memory and CPU, unstable system.

**Comment by mosfetish** [comment]
Normal CPU and memory consumption without SB user setting:

![subtle_brackets_good](https://user-images.githubusercontent.com/6182539/45457737-88779e80-b744-11e8-9568-4a8585c5a99b.png)

High CPU and memory consumption with SB user setting:

![subtle_brackets_bad](https://user-images.githubusercontent.com/6182539/45457743-91687000-b744-11e8-9bd7-d79efde85370.png)

**Comment by mosfetish** [comment]
It doesn't matter which user settings are applied, same problem. For these examples I was using:

```
"subtleBrackets.pairs": [
         "{}",
         "[]",
         "()"
     ]
```

Also, the high CPU/memory process won't let go even after closing Code. I have to kill it with the process manager, and it takes a long time to die. It's nasty.

**Comment by rafamel** [comment]
What's your Subtle Brackets version?

**Comment by mosfetish** [comment]
3.0.0

**Comment by rafamel** [comment]
The api for settings changed on v3. You changed they key but not the contents of the settings, which might explain it trying to do things it should not be doing. Could you please check with this:

```javascript
"subtleBrackets.pairs": [
  { "open": "(", "close": ")" },
  { "open": "[",  "close": "]" }, 
  { "open": "{", "close": "}" }
]
```

**Comment by mosfetish** [comment]
That works fine.

But I don't understand. The extension and my settings were working fine until a few days ago. If there was an automatic upgrade to the extension, are you saying the upgrade was incompatible with the settings?

**Comment by rafamel** [comment]
Yes, the upgrade was incompatible. It was a major version change. I will leave this issue open until I include some way to prevent old settings being read.

**Comment by SimoB** [comment]
I had the same problem, changelog is not updated so I didn't know about the v3 api change.
Also with prism parser enabled the pair <> is not working anymore!

**Comment by rafamel** [comment]
Thanks for reporting, guys. @SimoB , you're totally right, it should have gone into the changelog. I haven't updated it for the last few versions, and that's on me. I'll try to update it as soon as I can. However, keep in mind most of us are using semver, meaning a major version change will imply some non backwards compatible changes in the api, as it was the case. The keys for the settings were also changed, and all the new settings are detailed in the documentation.

Regarding the pair <> not working anymore, that makes sense as it is parsed and the parser looks for valid brackets for the language. You can skip parsing for any given pair by doing `parse: false` on the pair definition:

```javascript
"subtleBarckets.pairs" : [
  {
    "open": "<",
    "close": ">",
    "parse": false
  }
]
```

Again, I'll close this issue once:
* Changes are reflected in the changelog.
* Incompatible settings, even if in the correct key, are not read.
