### ISSUE TITLE
Issue with Bracket Matching Highlighting

### ISSUE THREAD

**Issue by carpet92** [rafamel/subtle-brackets#2]
Windows 10 Version 1703 Build 15063.413
VSCode v.1.13.1
Subtle Match Brackets v.2.0.0
[Material Theme](https://github.com/equinusocio/vsc-material-theme/releases) v.0.0.17

Other Installed Extensions:

[Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) v.1.1.1

Wrong bracket matching highlighting if on top we have commented code snippet using block comments.

I record a video to show what happens:

https://youtu.be/BPjKUSWNigw

My VSCode config:

```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 17,
    "editor.fontFamily": "Consolas",
    "editor.tabSize": 4,
    "git.enabled": true,
    "explorer.openEditors.visible": 9,
    "explorer.enableDragAndDrop": true,
    "files.encoding": "utf8",
    "files.eol": "\r\n",
    "files.insertFinalNewline": true,
    "files.autoSave": "off",
    "window.openFilesInNewWindow": "default",
    "editor.renderWhitespace": "none",
    "window.zoomLevel": 0,
    "workbench.welcome.enabled": true,
    "editor.lineHeight": 24,
    "editor.fontLigatures": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "material-theme-icons",
    "editor.minimap.enabled": true,
    "editor.dragAndDrop": true,
    "editor.minimap.renderCharacters": false,
    "editor.cursorBlinking": "blink",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "editor.mouseWheelZoom": false,
    "editor.renderIndentGuides": true,
    "editor.renderLineHighlight": "all",
    "editor.matchBrackets": false,
    "diffEditor.renderSideBySide": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "extensions.autoUpdate": false,
    "subtleBrackets.disableNative": true,
    "subtleBrackets.parse": true,
    "subtleBrackets.styles": {
        "global": {
            "borderWidth": "1px",
            "borderStyle": "none none solid none",
            "borderColor": "#FFCC00"
        }
    }
}
```

Code from video:

```javascript
router.get('/product/:id', function(req, res, next) {
	Product
		.findOne({
			_id: req.params.id
		})
		.populate('review', {
			data: {
				$slice: [0, 5]
			}
		})
		.exec(function(err, foundProduct) {
			res.render('main/product', {
				product: foundProduct
			})
		})
})

router.post('/review', function(req, res, next) {
	Review.findOne({
		product: req.body.this_product_id
	}, function(err, foundReview) {
		if (err) throw err
	
		foundReview.data.push({
			author: req.user.profile.name,
			author_email: req.user.email,
			content: req.body.review,
			date: new Date().toISOString(),
			recommended: ((req.body.recommended) ? true : false)
		})
	
		foundReview.save(function(err) {
			if (err) throw err
			callback(null, foundReview)
		})
	})
})
```

This issue not present with disabled `Subtle Match Brackets` extension on default VSCode"box" matching highlighting.

**Comment by carpet92** [comment]
@rafamel also I noticed that with "Plain Text" this not present. Only when syntax highlighting (JavaScript for instance) selected.

**Comment by rafamel** [comment]
This is due to the method by which subtleBrackets uses Prism to implement proper parsing. I've pushed a new version, it should now be solved. Thanks for reporting it and sorry for the delay on this! Tell me how it goes

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by Zx-EvM** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.

**Comment by carpet92** [comment]
@rafamel thanks a lot! Now that's works well. Thanks to your work now it's possible to use the familiar brackets matching highlighting style as in Sublime Text 3 in VSCode.
