### ISSUE TITLE
It is not working VS Code 1.26 or 1.27

### ISSUE THREAD

**Issue by aeciolevy** [rafamel/subtle-brackets#21]
Hello, 

I don't know it is not working on VS Code 1.26 and 1.27.2.

On the user settings, I am getting:
subtleBrackets.styles is the highlight as "Unknown configuration settings"

**Comment by kanlukasz** [comment]
+1 i have the same  (ver 1.31.1)

**Comment by rafamel** [comment]
Hi guys, the extension is working with VSCode latest (currently 1.32).

I'm assuming your issue has to do with Subtle Brackets v3 breaking changes regarding configuration. Please check the README and modify your settings if need be.
