### ISSUE TITLE
[FR] Highlight match from content

### ISSUE THREAD

**Issue by kanlukasz** [rafamel/subtle-brackets#24]
Hello

Great addon.
I have a question

It is possible to highlight matching brackets from content?

For example if i put cursor beetwen content:
![obraz](https://user-images.githubusercontent.com/30685349/57968020-6c786c80-7965-11e9-9df3-227559e45c47.png)
the brackets could be highlighted

**Comment by rafamel** [comment]
This is currently not possible. It'll leave it open as a FR to see whether it can be implemented in a future release.

**Comment by kanlukasz** [comment]
With the release in October, VSCode implemented this feature, it may be useful for you

![obraz](https://user-images.githubusercontent.com/30685349/68455344-746de680-01fb-11ea-9ad4-e67a5c4cf669.png)

**Comment by kanlukasz** [comment]
I browse my old tickets
Do you see any chance to implement this?

**Comment by kanlukasz** [comment]
Due to no response from the author for over a year, I decide closing this issue
