### ISSUE TITLE
Can I reuse your code?

### ISSUE THREAD

**Issue by CoenraadS** [rafamel/subtle-brackets#3]
Hello

I am the author of BrackerPairColorizer and want to switch my extension to also use PrismJS. I would like to use your code as reference since it achieves a similar task if it is ok with you.

Regards

**Comment by rafamel** [comment]
Sure, you've probably noticed it's MIT license. The current implementation does have an issue with template literals in Javascript. If you're able to make it work properly with them, I would very much appreciate a pull request or for you to let me know.

Rafa.
