### ISSUE TITLE
Error on subtleBrackets.bracketPairs

### ISSUE THREAD

**Issue by kenijo** [rafamel/subtle-brackets#4]
I wanted to report an error I get when trying to customize the subtleBrackets.bracketPairs setting.
As soon as I copy the default setting over to the user setting, I get the error message:
> Incorrect type.Expected "string[]"
![image 1](https://user-images.githubusercontent.com/5394591/32629572-efc7f16a-c556-11e7-829f-9588e30c61f1.png)

What I wanted to do is extend subtle-brackets to handle:
- double quotes "
- single quotes '
- tags < >

**Comment by rafamel** [comment]
Hi! Thanks for reaching out and sorry for the delay. The incorrect type error should now be solved (after updating to the latest Subtle Brackets version).
