### ISSUE TITLE
Slow to load

### ISSUE THREAD

**Issue by mrchief** [rafamel/subtle-brackets#5]
It seems to take a few seconds after the editor opens for this extension to kick in. I've tried with `subtleBrackets.parse: false` but the startup lag remains. 

I'm running Win7 x64 on a i7, 14GB RAM, SSD configuration so I know its not the typical HDD lag.

**Comment by rafamel** [comment]
Have you tried disabling all other extensions? It could be that the lag is caused by them and since you do expect a visual cue from subtle brackets you might only notice it there.

**Comment by rafamel** [comment]
I was keeping this open, I'll assume the issue didn't persist any further :)
