### ISSUE TITLE
Use fontStyle or at least fontWeight for brackets

### ISSUE THREAD

**Issue by vforsh** [rafamel/subtle-brackets#6]
Is it possible? I really would like to make matching brackets bold.
It will improve readability a lot.

**Comment by rafamel** [comment]
Hi Vladislav, the Subtle Brackets api is limited by VSCode API for [DecorationRenderOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions), so it's not something that depends on me. You can use any of those render options within the `subtleBrackets.styles` (maybe setting a color with more contrast will produce a similar gain on visibility for you)
